version: "3.5"

services:
  api01: &api
    image: rodrigotopan/rinha-backend-rodrigo-topan:1.0.0
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      - redis-server
    environment:
      - REDIS_CONNECTION_URL=redis://redis-server:6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  redis-server:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.33"
          memory: "240MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1