version: "3.5"

services:
  api01: &api
    image: rodrigotopan/rinha-backend-rodrigo-topan:1.0.6
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      - transaction-manager
    environment:
      - TRANSACTION_MANAGER_URL=http://transaction-manager:9000
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "8082:8080"

  transaction-manager:
    image: rinha-backend-transaction-manager rodrigotopan/rinha-backend-transaction-manager:0.0.5-in-memory
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "300MB"
 
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1