version: "3.5"

services:
  api01: &api
    image: rodrigotopan/rinha-backend-rodrigo-topan:1.0.5
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      - transaction-manager
    environment:
      - TRANSACTION_MANAGER_URL=http://transaction-manager:9000
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "8082:8080"

  transaction-manager:
    image: rodrigotopan/rinha-backend-transaction-manager:0.0.3
    ports:
      - "9000:9000"
    depends_on:
      - memcached
    environment:
      - MEMCACHED_CONNECTION_URL=memcached:11211
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  memcached:
    image: memcached:alpine # Usando a imagem do Memcached
    ports:
      - "11211:11211" # Mapeamento da porta padrão do Memcached
    deploy:
      resources:
        limits:
          cpus: "0.33"
          memory: "240MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1